### ISSUE TITLE
Allow the spark based test to use different spark contexts

### ISSUE THREAD

**Issue by piotrszul** [aehrc/VariantSpark#100]
Make is somehow possible to group tests based on the spark context then need.
Currently only one context is possible for all tests, while three different context are needed
- a basic local context (for most of the tests)
- a hail configured local contex (for hail test)
- a mulithreaded local context for ReproducibilyTest

**Comment by piotrszul** [comment]
Here is a good resource on how to do it with maven:

https://www.baeldung.com/maven-integration-test

**Comment by rocreguant** [comment]
It is implemented
