### ISSUE TITLE
pom.xml has the same dependancy twice

### ISSUE THREAD

**Issue by Yatish0833** [aehrc/VariantSpark#113]
<dependency>
		    <groupId>org.json4s</groupId>
		    <artifactId>json4s-ext_${scala.binary.version}</artifactId>
		    <version>3.2.11</version>
		</dependency>

This dependancy is there twice. Affecting the maven build.

**Comment by Yatish0833** [comment]
Very trivial thing. I thought it was affecting my maven build but it was just a warning.

**Comment by rocreguant** [comment]
It seems to be solved (the dependency has been commented out)
