### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by BauerLab** [aehrc/VariantSpark#13]
A python API needs to be added

**Comment by piotrszul** [comment]
Python API for generic variant-spark  interface.

Should be implemented in `variants` module in `python` directory.

The main access point should be `VariantsContext`  which can be used to load features and labels.
The API should be based on the 'non-depricated' scala api (from au.csiro.variantspark.api)

The general use pattern should he like this

```
from variants import VariantsContext
vc = VariantsContext(spark)
features = vc.import_vcf(input_path = "path-to-a-vcf-file")
label = vs.load_label(input_path = "path-to-a-csv_file", col_name = "column-name)
imp_analysis = features.importance_analysis(label, n_trees = 1000, m_try_fraction = 0.1, ...)
oob_error = imp_analysis.oob_error
imp_vars_df = imp_analysis.important_variables()
# imp_vars_df is a spark.sql.DataFrame
```

Some guidance on the implementation can be found in the `variants.hail` module.

**Comment by piotrszul** [comment]
API implemented.
Some technical debts reported as new issues.
