### ISSUE TITLE
implement mTry

### ISSUE THREAD

**Issue by BMJHayward** [aehrc/VariantSpark#135]
implement mTry as outlined in` RandomForestArgs.scala`

`@Option(name="-rmt", required=false, usage="RandomForest: mTry(def=sqrt(<num-vars>))" , aliases=Array("--rf-mtry"))
val rfMTry:Long = -1L
`

To be -accessible in  cli and api modules

**Comment by rocreguant** [comment]
I think it is already implemented. Please reopen if that's not the case...
