### ISSUE TITLE
GRCh38 reference genome with Hail based Variant Spark

### ISSUE THREAD

**Issue by schonbej** [aehrc/VariantSpark#137]
When trying to use Variant Spark with the hail interface on UK biobank whole exome sequencing data (reference genome GRCh38) I get the error
>Hail version: 0.2.16-6da0d3571629
>Error summary: IllegalArgumentException: requirement failed: The key needs to be (for now): (locus<GRCh37>, alleles: array<str>)

It would be great if hail based variant spark could also support GRCh38

**Comment by piotrszul** [comment]
@schonbej  would you be able to upload a small sample of a vcf file with this reference genome so that I can test it?

**Comment by schonbej** [comment]
@piotrszul It wouldn't let me upload a file that didn't end in .txt, but this is a vcf with 107 variants.
[small_table.txt](https://github.com/aehrc/VariantSpark/files/4412992/small_table.txt)

**Comment by schonbej** [comment]
Missing genotype calls in my dataset passed to random_forest_model as x cause a NullPointerExeption when trying to call fit_trees on the model.
For now I'll try to filter out sites with missing genotypes with hail, but it would be great if variant spark could handle this.

Code:
> rf_model = vshl.random_forest_model(y=c2s_mt.sample_membership.sample, x=c2s_mt.GT.n_alt_alleles())
> rf_model.fit_trees(500, 100)

Error message:
[fit_trees_nullpointer_exception.txt](https://github.com/aehrc/VariantSpark/files/4424323/fit_trees_nullpointer_exception.txt)
