### ISSUE TITLE
Predict Labels with VariantSpark

### ISSUE THREAD

**Issue by ArashBayatDev** [aehrc/VariantSpark#140]
VariantSpark offers RandomForest training with the "importance" command. I was wondering if you could implement prediction command too. I expect the prediction command to
accept feature values for the new set of samples similarly that the importance command accepts it ("-if" input file, "-it" input type, ....)
accept the model previously trained by "importance"  command through "-im" (input model parameter)
output a two-column file with sample id and predicted label. But that would be great to see more columns to show how many trees vote for each label.
An extension would be to implement probability prediction that for each sample reports the probability of each class. A further extension is to report it per tree (what is the probability of each class for each sample based on each tree)

I would like to see this in CLI first and then Hail API. If possible it would be nice to appear in Python API and then other API too.

Given that not all features from the input file are used in the RandomForest model, I strongly recommend not to load the entire input file in the memory but only features which are used in the model. Note that the input file could be really big.

Also if there was a feature in the model that is not reported in the input file the program should exit with a proper message and list all the features missing in the input file.

**Comment by BMJHayward** [comment]
I've been tossing up between serialising the file to disk as a json object, or possibly even converting to ONNX format. For the sake of time I'd recommend saving as json and adding ONNX later on.

To compare with this example:

```
./variant-spark --local -- importance
  -if data/chr22_1000.vcf  
  -ff data/chr22-labels.csv  
  -fc 22_16051249  
 -om modelFile.model  //new parameter to add to this command  
  -v -rn 500 -rbs 20 -ro
```

how about something like:

```
./variant-spark --local -- predict
  -if modelFile.model
  -im 22_16051249
  -of 22_16051249_predictions.file
```

Is this close to what you're after?

**Comment by piotrszul** [comment]
I think it should be something like: 

```
./variant-spark --local -- predict
  -if  to_predict.vcf  # or other supported input format/specification
  -im modelFile.model  # the serialized model from training 
  -of to_predict_predictions.csv
  # other options e.g.  if should output class probabilities
```

Where the output csv has the following format:
```sample, predicted_class, p_0, p_1, p_2, .... ```
where:
-```sample``` : sample id
-```prediced_class```:  the predicted class (max probability class)
_```p_0, p_1, p2```:  probability of each class
 
@ArashBayatDev what do you think?

**Comment by piotrszul** [comment]
@BMJHayward wrote: 
> Looking at ModelConverter.scala and ModelOutputArgs.scala, I'd like to be able to load a model previously serialised by the saveModel function. I.e. I want to be able to perform the inverse of the functionality here.
> @piotrszul what is the recommended approach here? Or even better, do you know of some code to do this already?
> AnalyzeRFCmd.run() might be good too

Yes, the code for serialization and (partialy) deserialization is in the classes you mentioned.
But ideally it should be refactored to a lower level API trait and classed that can handle serialisation and deserialisation in different formats.

**Comment by piotrszul** [comment]
I think we need to splits this into a few issues (and do them in this order):

- Implementing command line  prediction of class  form java serialised model 
- Add  command line option for predicing class probabilities
- Implementing command line  predictions form JSON serialised model
- Adding option for checking if the features in the prediction data match the model
- Implementing the same functionality in Hail API
- Implementing the same functionality in Python API
- Add support for ONYX 

@ArashBayatDev ???

**Comment by BMJHayward** [comment]
Yes I think so as well. To clarify something in point 4:
> Adding option for checking if the features in the prediction data match the model    

Do you mean validating features of input data before running prediction?

**Comment by piotrszul** [comment]
> Yes I think so as well. To clarify something in point 4:
> 
> > Adding option for checking if the features in the prediction data match the model
> > Do you mean validating features of input data before running prediction?

Yes, at minimum or more more general, the ability to deal with input data that have to some degree  different format, shape etc, than the training data.  I think this needs a bit of further discussion a for how much robustness needs to be built, the weakest option being none - garbage in garbage out. 
In the first stage I think we can make the requirement that the data for prediction exactly match the format, shape etc. of the data used for training. And then optionally add functionality to relax parts of this assumption.

**Comment by BMJHayward** [comment]
Ok I've a got a table here to represent the target output from @piotrszul above. I realised there could be a number of different ways to do this, and it could get complicated with things like multi-indices etc. Are my changes to the headers ok? @ArashBayatDev 

[predictionOutput.txt](https://github.com/aehrc/VariantSpark/files/4615172/predictionOutput.txt)

Notice the repetition of the sample ID, once for each sample location in the source vcf. Under this schema there would be (number of samples x number of locations) number of rows in the output.

Is this the _right_ implementation of what you mentioned above Peter?

Also note that I've got homozygous and heterozygous column names in place of 0|0, 0|1 and 1|1 for the alleles in each sample.

**Comment by BMJHayward** [comment]
Finally getting back to this after moving house and a lot of other big things happening.
Here's my current terminal output after running a predict command on a previously saved model.

![Selection_408](https://user-images.githubusercontent.com/7731287/96703922-2982ba00-13df-11eb-8984-13f010b554e7.png)

Produced with the command `./bin/variant-spark --local -- predict -if data/chr22_1000.vcf -ff data/chr22-labels.csv -fc 22_16050612 -om target/ch22-model.java -omf java -sr 13 -im data/ch22-model.java
`
This is on the branch https://github.com/bmjhayward/VariantSpark/tree/predictCmd

If it's suitable @ArashBayatDev  and @piotrszul I can clean it up and make a PR.

Let me know what you think.
