### ISSUE TITLE
How to de-serialise a previously stored model

### ISSUE THREAD

**Issue by BMJHayward** [aehrc/VariantSpark#144]
Looking at ModelConverter.scala and ModelOutputArgs.scala, I'd like to be able to load a model previously serialised by the `saveModel` function. I.e. I want to be able to perform the inverse of the functionality here.

@piotrszul what is the recommended approach here? Or even better, do you know of some code to do this already? 

`AnalyzeRFCmd.run()` might be good too

**Comment by piotrszul** [comment]
@BMJHayward  i will respond in: #140
