### ISSUE TITLE
Clustering sample 

### ISSUE THREAD

**Issue by TaniaCuppens** [aehrc/VariantSpark#165]
Hi,

I am currently testing your tool to cluster a large number of individuals according to their ethnicity or phenotype. I used the "importance" option but this allows to give importance to the variants and not to cluster individuals. What would be the command to be able to do that. Something like what you did in your first publication :
O’Brien, A.R., Saunders, N.F.W., Guo, Y. et al. VariantSpark: population scale clustering of genotype information. BMC Genomics 16, 1052 (2015)

Thanks a lot

**Comment by rocreguant** [comment]
Are you still interested in that?

**Comment by rocreguant** [comment]
I'm closing the issue since we haven't heard back.
Feel free to re-open with this or any new issue :)
