### ISSUE TITLE
Enable running variant spark on AWS EMR

### ISSUE THREAD

**Issue by piotrszul** [aehrc/VariantSpark#17]
This will include:
- variant-spark setup on EMR 
- fixing any issue that may arise (like local filesystem writes etc)
- scrips to facilitate creation of variant-spark enabled EMR cluster
- scrips to submit variant-spark commands to EMR cluster
- demo and documentation

**Comment by lynnlangit** [comment]
Has this item been completed? If so would you like me to test the scripts?  After verifying, I can also update the README.md file.

Another consideration might be to create an AWS CloudFormation template (which would encapsulate the setup scripts) to make setup on AWS even simpler.

**Comment by piotrszul** [comment]
Still working at it @lynnlangit, but it would be great if you could help testing/documenting it.  CF template sound like a great idea. Once I get sometime working I will also value your advice on the 'user experience' aspect.

**Comment by piotrszul** [comment]
The first version is ready. Check the https://github.com/aehrc/VariantSpark/tree/master/cloud/aws-emr for more info.
