### ISSUE TITLE
NoClassDefFoundError after running VariantSpark (CLI)

### ISSUE THREAD

**Issue by bendruitt** [aehrc/VariantSpark#18]
After installing the VariantSpark environment (Java, Spark, Scala) and building VariantSpark using documentation, execution of VariantSpark from the terminal results in:

Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/ManifestFactory$
	at au.csiro.variantspark.cli.VariantSparkApp$.main(VariantSparkApp.scala:23)

This can be caused by not setting the SPARK_HOME environment variable to:

export SPARK_HOME=<your-spark-installation-dir>

Using a package manager such as Homebrew may sidestep this problem.

**Comment by hkeward** [comment]
I am having the same issue when trying to run one of the example scripts. Here is the full output:

```
/VariantSpark-master# ./scripts/local-run-importance-ch22.sh 
/VariantSpark-master/variant-spark --local -- importance -if /VariantSpark-master/data/chr22_1000.vcf -ff /VariantSpark-master/data/chr22-labels.csv -fc 22_16051249 -v -rn 500 -rbs 20 -ro
/VariantSpark-master/conf:/VariantSpark-master/target/variant-spark_2.11-0.2.0-SNAPSHOT-all.jar:/spark-2.1.0-bin-hadoop2.7/bin//jars/*:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/.//*:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/*:/usr/lib/hadoop-hdfs/.//*:/usr/lib/hadoop-yarn/lib/*:/usr/lib/hadoop-yarn/.//*:/usr/lib/hadoop-mapreduce/lib/*:/usr/lib/hadoop-mapreduce/.//*
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/ManifestFactory$
	at au.csiro.variantspark.cli.VariantSparkApp$.main(VariantSparkApp.scala:25)
	at au.csiro.variantspark.cli.VariantSparkApp.main(VariantSparkApp.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.ManifestFactory$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

```

I have tried installing different versions of scala, and I have tried setting SCALA_HOME to various things. I have also tried not installing scala at all since it seems like maven installs it when I run `maven clean install`, though I'm not very familiar with maven so this may not be the case.

Also -- I am doing all of this in Docker, based on Ubuntu xenial.

**Comment by piotrszul** [comment]
The issue with using the `--local` mode is that it needs `SPARK_HOME` to be set and did check for it or produce a useful error message.

But in general `--local`  mode should be avoided and instead `--spark --master local` should be used   (which is the default)

I have updated the command line script to check for `SPARK_HOME` and  `spark-submit` as well as update the sample scripts to use `--spark --master local`.

We are currently working on a better  use documentation, which should clarify that further.
