### ISSUE TITLE
VariantSpark_HipsterIndex_Spark2.scala does not work with Spark 2.2

### ISSUE THREAD

**Issue by piotrszul** [aehrc/VariantSpark#20]
The R code in the sample notebook does not work with Spark 2.2:
<img width="1038" alt="screen shot 2017-08-18 at 6 25 57 pm" src="https://user-images.githubusercontent.com/3760778/29799556-b39cdd8c-8ca7-11e7-8da5-8ceb517c83ca.png">

**Comment by piotrszul** [comment]
As per: https://docs.databricks.com/spark/latest/sparkr/overview.html
since 2.2 SparkR needs to be loaded explicitly and it also appears that the old syntax with sqlContext is not longer supported.

**Comment by piotrszul** [comment]
Updated R code to work with Spark 2.2.
@lynnlangit  could you please import the new notebook from the https://aehrc.github.io/VariantSpark/notebook-examples/VariantSpark_HipsterIndex_Spark2.html

**Comment by lynnlangit** [comment]
tested and working - thanks
