### ISSUE TITLE
How to use vcf file?

### ISSUE THREAD

**Issue by cmorris2945** [aehrc/VariantSpark#216]
I am trying to use the .vcf file in Databricks,
but I am not seeing anywhere in the readme file
on how to USE to vcf file?

How do you use the vcf file specifically?

**Comment by rocreguant** [comment]
We use [Hail](https://hail.is/) to load and manipulate the data.
But to pass the data to VariantSpark we transform it into a genotype matrix using `mt.GT.n_alt_alleles()`

**Comment by cmorris2945** [comment]
Hello. Can send the documentation over for that function in python??  Unless is it part of 'hail'?

**Comment by rocreguant** [comment]
That is [Hail](https://hail.is/)

**Comment by cmorris2945** [comment]
ok understood
