### ISSUE TITLE
HADOOP ERROR SERVICE AWS....

### ISSUE THREAD

**Issue by cmorris2945** [aehrc/VariantSpark#217]
<img width="1649" alt="Screen Shot 2022-08-04 at 11 02 22 AM" src="https://user-images.githubusercontent.com/30676606/182880795-570828ae-afb5-4cbb-af25-c7253dda1587.png">

Hello. Can you tell me if the Hadoop server is still up and running?
Because I am getting a lot of memory and "missing file errors" as well.

Can you tell me what the problem is?

-CHRIS

**Comment by rocreguant** [comment]
You can consider checking: https://aws.amazon.com/marketplace/pp/prodview-pgna4dj6xqqde

**Comment by cmorris2945** [comment]
Is this the new variant spark notebook version on AWS?
Because I already ran this. This is where I got the error before.
I get "roll-back" errors when it starts

**Comment by rocreguant** [comment]
it says out of memory

**Comment by cmorris2945** [comment]
Ok, well is there a way to increase the memory?
Do I do it in the configuration file script that comes with the
variant spark notebook configuration?

Because the way it works now, is you need an AWS account,
then you can run the variant spark notebook with it's
template, or you can make one yourself.

**Comment by rocreguant** [comment]
Get nodes with more memory in AWS. But it largely depends on your data.
You can also try to run it on your cluster.
Try a smaller batch size.

**Comment by cmorris2945** [comment]
Are you sure that's the issue? Just lack of memory?

Right now I'm just trying to get the demo
version up and running which includes
their own data concerning the disease ALS.

After I get the demo version running I will replace it with my
own VCF files.

**Comment by rocreguant** [comment]
We're experiencing no issues.
But open discuss partnership options if your problems persist.

**Comment by cmorris2945** [comment]
What's "partnership options"?

**Comment by rocreguant** [comment]
We're committed to maintaining and further improving this tool but we cannot offer personalized support.
For custom-made solutions and collaborations, you can look at: https://aehrc.csiro.au/work-with-us/
