### ISSUE TITLE
Add support for ingesting non-VCF data sources using DataBricks scala API

### ISSUE THREAD

**Issue by bendruitt** [aehrc/VariantSpark#31]
At present only VCF files are exposed using the scala API for ingesting feature data. It would be useful to allow easy ingestion of parquet files as this would broaden the usefulness of VariantSpark beyond genomics. The class ParquetFeatureSource appears to offer this functionality already but is not available within the Databricks environment.

**Comment by rocreguant** [comment]
Not relevant anymore
