### ISSUE TITLE
Add generation of fake families

### ISSUE THREAD

**Issue by piotrszul** [aehrc/VariantSpark#59]

**Comment by piotrszul** [comment]
The input will be the vcf file and the desired offspring with their pedigree encoded as family triples, e.g.:

offspring_ID mother_ID
father_ID
OFF1 FOUND1
FOUND2
OFF2 OFF1
FOUND3

etc.

You can create the pedigree file manually or generate is automatically, to create any structure you want and variant-spark will generate genotypes for all offsprings.
If we want to account for gender then it  should also be included in the pedigree file, and you should make sure that the offspring gender matches it’s parental role (if used as parent for next generation), so maybe something like:

offspring_ID sex  mother_ID father_ID
OFF1 F
FUND1 FOUND2
OFF2 M
OFF1 FOUND3
OFF3 M
FOUND4 OFF2
etc.

The output will be a vcf file with all the FOUNDERS and OFFSPRINGS + a file with detailed info about the parameter of each reproduction (all crossing over points used for father and mother zygotes and all mutations)

**Comment by natwine** [comment]
Hi Piotr,

All looks good. I have made a ped file containing unrelated CEU genomes from 1000K. There are 113 to be used as founders. If we need more, there are further caucasian populations in the 1KG set.

I have attached the HapMap recombination  as well for use at each meiosis.

**Comment by piotrszul** [comment]
Core functionality implements.
The improvements/debt captured in: [#69]FakeFamily improvements
