### ISSUE TITLE
FakeFamily improvements

### ISSUE THREAD

**Issue by piotrszul** [aehrc/VariantSpark#69]
Some ideas on how to improve fake family generation:
- Add reading all files from HDFS (including ped and spec)
- Review and improve hail support for phased genotypes
- Added one pass generation of independent mutations( generate mutation for all individuals in one pass and distribute them per individual)
- Scala/Python API for fake family generation
- Performance improvements for offspring genotype generation (use indexed sequence rather than HashMap)
- Add mutations based on fasta (actual sequence file)

**Comment by rocreguant** [comment]
Too far from VS core functionality
