### ISSUE TITLE
Adding ALT field to output file

### ISSUE THREAD

**Issue by ArashBayatDev** [aehrc/VariantSpark#83]
In the output file of importance analysis, each variant is identified with its site that is the combination of CHR_POS. However, there are cases that multiple bi-allelic variants appear in the same site. It would be great to add the ALT field to the output file such that each variant is identified as CHR_POS_ALT. This can resolve the ambiguity.

**Comment by piotrszul** [comment]
Added options to `importance` command:

  @Option(name="-ivb", required=false, usage="Input vcf is biallelic (def=false)", aliases=Array("--input-vcf-biallelic"))

  @Option(name="-ivs", required=false, usage="The separator to use to produce labels for variants from vcf file.(def='_')", aliases=Array("--input-vcf-sep"))


Also fixed a bug with encoding of multialleic non ref hetero genotypes (were encoded as 1 instread of 2)
