### ISSUE TITLE
Output trees in JSON format

### ISSUE THREAD

**Issue by BauerLab** [aehrc/VariantSpark#89]
Implement a readable output e.g. JSON for the trained trees. This will help evaluate the resulting interactions and visualise them.

**Comment by piotrszul** [comment]
Implemented:
`-omf` option can be now used to define the format for model saved with `-om`
Valid formats are:

 - `java` (default) for binary java serialization format
- `json` for test JSON format

e.g.:

`variant-spark importance .... -om  'model.json' -omf json `

**Comment by rocreguant** [comment]
implemented
