### ISSUE TITLE
Create automatic launch function for VariantSpark to AWS

### ISSUE THREAD

**Issue by BauerLab** [aehrc/VariantSpark#95]
Create an automated way to spin up a Spark cluster on AWS with VariantSpark installed so researchers can get started easily. 

This extends the work done by Lynn Langit as detailed over the following three blog posts:
Part 1: [Getting Started with VariantSpark and cloud deploy](https://medium.com/@lynnlangit/scaling-custom-machine-learning-on-aws-d9dc7edfbff9) 
Part 2: [Using EMR to deploy](https://medium.com/@lynnlangit/scaling-custom-machine-learning-on-aws-part-2-emr-6dfc3cd91a1f)
Part 3: [Using EKS to deploy](https://medium.com/@lynnlangit/scaling-custom-machine-learning-on-aws-part-3-kubernetes-5427d96f825b)

**Comment by rocreguant** [comment]
done
